### ISSUE TITLE
IRC-js doesn't handle timeouts gracefully

### ISSUE THREAD

**Issue by jfhbrook** [gf3/IRC-js#1]
Hey there!

I've been using IRC-js to make a bot, and inevitably, I eventually get this error:

```
...(more pongs, privmsgs, etc)...
[SENT] PONG :calvino.freenode.net
[SENT] PONG :calvino.freenode.net
[SENT] PONG :calvino.freenode.net
[SENT] PONG :calvino.freenode.net
[SENT] PONG :calvino.freenode.net
[SENT] PONG :calvino.freenode.net
[SENT] PONG :calvino.freenode.net
[SENT] PONG :calvino.freenode.net
[SENT] PONG :calvino.freenode.net


events:11
        throw arguments[1];
                       ^
Error: ETIMEDOUT, Connection timed out
    at IOWatcher.callback (net:871:22)
    at node.js:266:9
```

(It's a pretty quiet bot.)

I'm not really sure how to fix this, since I'm not intimately familiar with IRC-js's internals and I'm pretty new to node (and javascript in general, actually).

**Comment by gf3** [comment]
Thanks, I'll look into it. I'll try and see if I can reproduce a timeout.

**Comment by jfhbrook** [comment]
Cool! Thanks.

**Comment by jfhbrook** [comment]
It turns out that the timeout was actually due to something I wrote. D-oh! As far as I know, IRC-js works just fine.

Issue: Closed!

**Comment by gf3** [comment]
Awesome, good to know, thanks!
