### ISSUE TITLE
ZNC

### ISSUE THREAD

**Issue by guybrush** [gf3/IRC-js#10]
I am using ZNC (http://en.znc.in/wiki/ZNC), which is an IRC-Bouncer. 

Connecting to ZNC with IRC-js (current HEAD) does not work for me. I tried to connect my Jerk-bot to the ZNC-bouncer, there are no errors - it just does not say anything.

Maybe it is a ZNC-releated bug?

**Comment by callumacrae** [comment]
Just saying, did you remember to send the password to the server before you sent anything else, and connect to the right port?

**Comment by guybrush** [comment]
yes

i am using node-irc from @martynsmith now and it works all fine
