### ISSUE TITLE
handling ECONNREFUSED/ECONNRESET (and others)

### ISSUE THREAD

**Issue by nail** [gf3/IRC-js#11]
Hello,

First, thanks for this module :)

I noticed we have no access to the private stream property and this makes it difficult to handle network errors and automatic reconnections. I am not 100% confident this is the right solution, but what about adding:

```
stream.addListener('error', do_disconnect.bind(this));
```

inside the connect method, along with the data/timeout/end handlers?

Regards,
Renaud Drousies

**Comment by gf3** [comment]
Thanks for the kind words, Renaud. This seems reasonable as long as all error messages are fatal. I'll have to search around to be sure as we wouldn't want bots disconnecting for non-fatal errors.

Or, would you rather be able to listen for error messages directly and disconnect if you see fit?

**Comment by nail** [comment]
Actually yes, emitting another event instead of calling do_disconnect might be more flexible.

As a side note, I'm playing around with your library, and I'm experiencing an issue with the way net.Stream works. 

I've modified your module this way:

```
stream = net.createConnection( this.options.port, this.options.server )
stream.addListener('error', do_disconnect.bind(this));
```

The problem I have is that it looks like sometimes the listener is not registered fast enough and the error is not caught, hence it does throw the ECONNREFUSED exception.

This looks like it's a problem with node.js and not your module, I'm not sure if there's a way to work around it besides handling the exception manually... Or it's maybe the way I'm using the module which is wrong :)

Regards,
Renaud

**Comment by nail** [comment]
Ah, there's a workaround for it (thanks to stride - #node,js)

To make sure the events are correctly caught, changing the connection creation to the following fixed the problem:

```
  stream = new net.Stream();
  stream.setEncoding( this.options.encoding )
  stream.setTimeout( 0 ) 
  stream.addListener('error', do_disconnect.bind(this));
  stream.addListener( 'data', parseMessage.bind( this ) ) 
  stream.addListener( 'timeout', do_disconnect.bind( this ) ) 
  stream.addListener( 'end', do_disconnect.bind( this ) ) 
  stream.connect(this.options.port, this.options.server);
```

That fixed my problem of having the net.createConnection errors sometimes emitted too early.

Regards,
Renaud

**Comment by gf3** [comment]
Oh nice! Would you be able to send me a pull request with those changes?
