### ISSUE TITLE
Fails parsing single quotes in nicknames

### ISSUE THREAD

**Issue by simenbrekken** [gf3/IRC-js#17]
The parser doesn't handle single quotes

<pre>
Failed parsing ':*.quakenet.org MODE #test12 +o test'
</pre>

**Comment by gf3** [comment]
Single quotes aren't legal in nicknames. The IRC message you included seems to be a server message, are you sure you meant to include that one?

**Comment by lorentzkim** [comment]
On that note, I believe I'm getting similar errors: https://gist.github.com/149544d4f1bcbe38a797

Section 2.3.1 of http://www.ietf.org/rfc/rfc1459.txt seems to suggest that any of -, [, ], \, `, {, and } are fine. And perhaps there isn't support for special characters? I did test on my personal server however, and it seemed to work fine with a nickname of "a-[]`{}". I'm not sure what could be wrong now.

There are two errors in there, and they seem to come from an identical issue.

I'm aware I'm still using 0.2.13 of irc-js, will upgrade to 0.2.14 and see if issue persists.

**Comment by gf3** [comment]
Lorentz, carets were added in the previous version. I've just added backticks in `0.2.15`:

![Backticks](http://f.cl.ly/items/1i1y342b0O202s344141/Screen%20shot%202011-02-07%20at%2012.56.06%20PM.png)
