### ISSUE TITLE
Join after connect doesn't work with Mibbit

### ISSUE THREAD

**Issue by sam1919** [gf3/IRC-js#19]
.connect( function(){ this.join(channel); }

works with freenode.org. It doesn't work with irc.mibbit.net.

**Comment by gf3** [comment]
Some networks don't allow you to instantly join channels on connect. To deal with this, I've been using a `setTimeout` in my libraries: https://github.com/gf3/Jerk/blob/master/lib/jerk.js#L30-35

If I can find a way to detect better readiness I will incorporate it into IRC-js, but for now `setTimeout` is probably the best solution.

**Comment by bergmark** [comment]
I'm looking at the RFC now trying to find a basis for this, I'm pretty sure it's there somewhere...

But anyway, in irc.js do_connect is called as soon as a line is received from the server, don't you have to wait until 001 is received before sending JOIN?

**Comment by gf3** [comment]
I don't think 001 is standardised or guaranteed though.
