### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by excid3** [gf3/IRC-js#20]
I attempted this myself, but frankly I don't have any idea where to begin.

**Comment by gf3** [comment]
I'll have a look at it. I know ryah has been doing a lot of work with crypto in the upcoming version of node, so this may have to wait until the release of the new API.

**Comment by excid3** [comment]
Thanks! I heard that was going on as well. I tried doing a simple setSecure on the stream, but that was just timing out the connection.

**Comment by excid3** [comment]
I upgraded to 0.4.0 (from 0.2.6) and got SSL support working with this commit: https://github.com/excid3/IRC-js/commit/5c8a9e0e59666c109ec7e5bd8a3d5f481ab78d32

Unfortunately I couldn't find a good way to create a new TLS stream like net has.

**Comment by gf3** [comment]
Boom, done. Just add `ssl: true` to your `options`.
