### ISSUE TITLE
Issues with UnrealIRCd

### ISSUE THREAD

**Issue by callumacrae** [gf3/IRC-js#23]
Originally reported here, but isn't an issue with Jerk:

https://github.com/gf3/Jerk/issues/10

_some filler text here_

**Comment by callumacrae** [comment]
Sending some text straight after connection works around the issue and allows the connection. Perhaps just PING the server?

EDIT: Oops, wrong button -__-

**Comment by gf3** [comment]
Okay, so I've finally gotten around to testing this out. It seems to be working for me, both with a delay and with sending text immediately. My bots aren't being disconnected.
