### ISSUE TITLE
Crashes on .quit()

### ISSUE THREAD

**Issue by martingms** [gf3/IRC-js#24]
When trying to end one of my irc-connections with .quit() (just one, mind you), the following happens:

```
[Tue, 24 May 2011 14:48:00 GMT] INFO       [RECV]  :lololol!js-irc@rox-2E398DDF QUIT :Client exited
[Tue, 24 May 2011 14:48:00 GMT] INFO       [RECV]  :lololol!js-irc@rox-2E398DDF QUIT :Client exited
[Tue, 24 May 2011 14:48:00 GMT] INFO       [RECV]  ERROR :Closing Link: lololol[localhost] (Client exited)

events.js:47
        throw new Error("Uncaught, unspecified 'error' event.");
              ^
Error: Uncaught, unspecified 'error' event.
    at EventEmitter.emit (events.js:47:15)
    at IRC.parseMessage (/Users/martin/src/node-web-irc/lib/IRC-js/lib/irc.js:138:15)
    at Socket.<anonymous> (native)
    at Socket.emit (events.js:64:17)
    at Socket._onReadable (net.js:671:31)
    at IOWatcher.onReadable [as callback] (net.js:177:10)
```

Using .disconnect() gives the same error.

**Comment by gf3** [comment]
Surprisingly, this is not an actual error. This is the IRC network saying "kthx bai". In Node, when an `EventEmitter` emits an `error` event, and there are no listeners, the default action is to throw that event as an error. To solve this, you can simply listen for the `error` event, and if it contains `"Closing Link"` you can safely ignore it.
