### ISSUE TITLE
'coloured-log' shouldn't be a bundled dependency...

### ISSUE THREAD

**Issue by TooTallNate** [gf3/IRC-js#27]
PanPG is ok since it's not already published on npm, but coloured-log needs to go. It can be installed from npm fine, and on top of that, the irc-js version that's currently up on npm has an incomplete checkout of 'coloured-log', it's dependencies aren't checked out. This leads to npm saying that irc-js is missing dependencies immediately after installation.

Just remove [this line](https://github.com/gf3/IRC-js/blob/a983e8f5bc49cbe4dc98281f886cbaa34b6f1c90/package.json#L21) and `rm -rf node_modules/coloured-log` and republish on npm and we should be good! Thanks in advance!

**Comment by gf3** [comment]
Indeed, I am going to be removing all (unnecessary) bundled dependencies from both Jerk and IRC-js soon. This was originally done to allow people to simply clone the repo and start using it, but now that npm has become ubiquitous I feel it is safe remove these deps.

**Comment by broofa** [comment]
Nice!  Yeah, I found those dependencies to be a bit annoying.

**Comment by TooTallNate** [comment]
See #32 for a pull request that fixes this...

**Comment by gf3** [comment]
Fixed in #32
