### ISSUE TITLE
IRC#names callback channel argument incorrect

### ISSUE THREAD

**Issue by Spotnyk** [gf3/IRC-js#28]
I might be doing something wrong, but when calling IRC#names, the callback 'channel' argument is always '='.

I'm not sure why this is happening. But I can reproduce it every time. It does provide the channel usernames correctly, just not the channel name itself.

**Comment by gf3** [comment]
Strange, looks like IRC servers deviate from the spec here. I'm not sure what the `=` means, but I have added the exception. I'll push it live soon.

**Comment by gf3** [comment]
Thanks!

**Comment by Spotnyk** [comment]
For reference, this was happening with the InspIRCd server. Thanks for the fix.

**Comment by gf3** [comment]
Same thing on ircd-seven and UnrealIRCD.
