### ISSUE TITLE
Connecting to ngIRCd does not work

### ISSUE THREAD

**Issue by jsyrjala** [gf3/IRC-js#38]
Connecting to [ngIRCd](http://ngircd.barton.de/) does not work because of the following:
1. ngircd server accepts incoming connection but send no data to client. 
2. The client (Jerk with irc-js) waits some kind of reply from the server before initiating the login (PASS, NICK and USER commands).  Thus the client sends no data to server.
3. server disconnects after 20 seconds or so.

I think that the correct behavior for the client is to send login commands right after connect, and not to wait for any data from the server. At least that is how clients like http://irssi.org/ do it.

**Comment by gf3** [comment]
Good catch, I'll have to test it out.

**Comment by gf3** [comment]
Maybe there is a way to detect this without the extra option?

**Comment by jsyrjala** [comment]
We could remove the option altogether, the client would always initiate the login right after connect. Would that cause problems with some servers? 

I see no way to auto-detect this server behaviour, except to wait few seconds after connect, and initiate login if server hasn't said anything. But then again, if server says something, the IRC-js initiates login anyway.

I will make pull request for you where the client always sends login commands  on connect

**Comment by gf3** [comment]
Fixed in bfa34db4c9406790692135d3b3f0ce5b8618421f
