### ISSUE TITLE
Issue installing irc-js

### ISSUE THREAD

**Issue by caleywoods** [gf3/IRC-js#44]
npm install irc-js
npm info it worked if it ends with ok
npm info using npm@0.2.17
npm info using node@v0.4.3
npm ERR! Error: ucs {bad_utf8_character_code}: irc-js
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node/.npm/npm/0.2.17/package/lib/utils/registry/request.js:154:16)
npm ERR!     at IncomingMessage.emit (events.js:81:20)
npm ERR!     at HTTPParser.onMessageComplete (http.js:132:23)
npm ERR!     at Client.onData [as ondata](http.js:1464:27)
npm ERR!     at Client._onReadable (net.js:675:27)
npm ERR!     at IOWatcher.onReadable [as callback](net.js:177:10)
npm ERR! Report this _entire_ log at http://github.com/isaacs/npm/issues
npm ERR! or email it to npm-@googlegroups.com
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm not ok

**Comment by caleywoods** [comment]
Closing, sorry just noticed it was on NPM not here.

**Comment by gf3** [comment]
Also it looks like you're using an older version of npm, don't forget to upgrade.

**Comment by caleywoods** [comment]
Yep, that's what fixed it. I brew installed npm and was able to get it running just fine.
