### ISSUE TITLE
Don't `console.info` everything

### ISSUE THREAD

**Issue by rauchg** [gf3/IRC-js#46]
Logging should be handled optionally.

**Comment by gf3** [comment]
I think it only does it once, on error: https://github.com/gf3/IRC-js/blob/master/lib/irc.js#L118

**Comment by rauchg** [comment]
Oh, didn't notice `this.options.log`. Thanks! It was a bit surprising that _every_ message read through IRC gets logged by default.

**Comment by gf3** [comment]
Do you think it should be false by default?

**Comment by rauchg** [comment]
Not a binary option, but a log level instead. By default log level is high enough that it doesn't log everything, but optionally you can.
