### ISSUE TITLE
I get an error when it is connected to irc server of ustream

### ISSUE THREAD

**Issue by potix** [gf3/IRC-js#47]
I get an error when it is connected to irc server of ustream using irc-js module.
It seems that irc server of ustream doesn't sent any data.  
But irc-js module  starts sending NICK command after recieving some data from irc sever of ustream.
Thus, irc-js times out.
Finally,  rc-js module  starts sending NICK command after recieving timeout message from  irc sever of ustream.
Please help me.

irc-js version 0.2.26

--- test.js ---
var irc = require('irc-js');
var options = {
   server           : 'chat1.ustream.tv',
   port             : '6667',
   encoding         : null,
   pass             : 'password',
   nick             : 'username',
   log              : true,
   die              : false,
   flood_protection : false,
   user             : {
       hostname   : 'localhost',
       servername : 'chat1.ustream.tv',
       username   : 'username',
       realname   : 'username'
   }
}
var ircInstance = new irc(options);
ircInstance.on('error', function(message) {
    console.log(message);
});
ircInstance.connect(function() {
    console.log('connected'); 
});

> node test.js 
> [RECV]  ERROR :Closing Link: [xxx.xxx.xxx.xx](Ping timeout)
> [SENT]  PASS password
> [SENT]  NICK username
> [SENT]  USER username 0 \* :username
> connected
> { command: 'error',
>   params: [ 'Closing Link: [xxx.xxx.xxx.xx](Ping timeout)' ],
>   raw: 'ERROR :Closing Link: [xxx.xxx.xx.xx](Ping timeout)\r\n' }

**Comment by gf3** [comment]
Do you know how long after connecting does it give you the error?

**Comment by gf3** [comment]
Is this still an issue on `2.0.0-beta`?

**Comment by potix** [comment]
When I used version 2.0.0-beta, it operated as expected. 
work fine.
thank you.
