### ISSUE TITLE
TypeError: path must be a string

### ISSUE THREAD

**Issue by curious-attempt-bunny** [gf3/IRC-js#61]
I'm following the documentation for the beta. Does this work for you?

$ npm install irc-js
npm http GET https://registry.npmjs.org/irc-js
npm http 304 https://registry.npmjs.org/irc-js
irc-js@2.0.0-beta.1 node_modules/irc-js

$  grep -A 2 engines node_modules/irc-js/package.json 
  "engines": {
    "node": ">=0.8.1"
  },

$ node -v
v0.8.19

$ node --harmony

> var irc = require("irc-js");
> undefined
> irc.connect({ nick: "bot500" }, function(bot) { } );
> TypeError: path must be a string
>     at Object.fs.openSync (fs.js:338:18)
>     at Object.fs.readFileSync (fs.js:182:15)
>     at getConfig (..../node_modules/irc-js/lib/irc.js:493:35)
>     at Object.quickConnect [as connect](..../node_modules/irc-js/lib/irc.js:515:26)
>     at repl:1:5
>     at REPLServer.self.eval (repl.js:109:21)
>     at rli.on.self.bufferedCmd (repl.js:258:20)
>     at REPLServer.self.eval (repl.js:116:5)
>     at Interface.<anonymous> (repl.js:248:12)
>     at Interface.EventEmitter.emit (events.js:96:17)

**Comment by gf3** [comment]
Sorry @curious-attempt-bunny, I've just pushed a more up-to-date version. Should be available on npm as well (`2.0.0-beta.2`).

**Comment by curious-attempt-bunny** [comment]
Thanks @gf3!
