### ISSUE TITLE
Undefined crash bug

### ISSUE THREAD

**Issue by unusualbob** [gf3/IRC-js#66]
I discovered that when connecting to twitch.tv's irc that the client crashed every time I connected.

Error is as follows:

```
\node_modules\irc-js\lib\message.js:112
    for (let j = 0, m = params[i].length; j < m; ++j) {
                                 ^
TypeError: Cannot read property 'length' of undefined
    at Message.toBuffer (\node_modules\irc-js\lib\message.js:112:34)
    at Client.send (\node_modules\irc-js\lib\irc.js:247:11)
    at Client.sendUser(\node_modules\irc-js\lib\irc.js:291:15)
    at Client.onConnect (\node_modules\irc-js\lib\irc.js:162:12)
    at Socket.EventEmitter.emit (events.js:117:20)
    at Object.afterConnect [as oncomplete] (net.js:883:10)
```

I found that simply wrapping the for statement there with an `if(params[i])` check seemed to solve the issue entirely. I am not sure if there's another underlying cause as I didn't exactly spend a large amount of time tracing the stack.

[Here's a link to the specified section of code.](https://github.com/gf3/IRC-js/blob/master/lib/message.js#L110)

**Comment by ghost** [comment]
Thanks for the report!
I signed up on Twitch and tried to reproduce, but I connected successfully.
Is there a possibility that an `undefined` (or something without a `length`) property is sent as a parameter in your bot code?
I suppose it couldn’t hurt to add some checks for that sort of thing, if only to produce nicer error messages.

**Comment by unusualbob** [comment]
I can replicate it with just this:

```
console.log('started');
irc.connect({
    nick: '[usernamehere]'
  , user: {
      password: '[passwordhere]'
  }
  , server: {
        address: 'irc.twitch.tv'
      , port: 6667
  }
}, function(ircClient) {
  console.log('connected');
});
```

Dev environment
- Windows 7 x64
- Node 0.8.25 & 0.10.22

Just to make sure it wasnt just my account causing some sort of issue (since mine is fairly old) I made a new test account on their servers and still got the same result.

**Comment by ghost** [comment]
Thanks again.
I was using a config file, with that code I can reproduce it.
Found the cause (`extend(defaultConfig, userConfig)` replacing the `user` object instead of adding/overwriting its properties), and will try to get a fix in soon.
