### ISSUE TITLE
Is this package dead?

### ISSUE THREAD

**Issue by deiga** [gf3/IRC-js#71]

**Comment by aaronj1335** [comment]
![hello dead i'm dad](https://cldup.com/-IICG0AMrP.gif)

i don't think so. what's up?

**Comment by deiga** [comment]
Well the 2.0 beta doesn't work properly and the last commit has been a year ago

**Comment by gf3** [comment]
@deiga we've been running bots on this codebase for years—it's been pretty stable for a while. might need a tiny bit of work to get it up to speed with node `0.12` but that's about it

**Comment by deiga** [comment]
@gf3 Yeah, I managed to get this working after initial struggles

**Comment by gf3** [comment]
@deiga let me know if i can help with anything!

**Comment by wesbos** [comment]
@deiga Let me know if I can help @gf3 with anything!

**Comment by kieran** [comment]
@wesbos Let me know if I can help you help @gf3 with anything!

**Comment by connerfritz** [comment]
@kieran Let me know if I can help you help @wesbos help @gf3 with anything!
