### ISSUE TITLE
Backticks in nick causes parse error

### ISSUE THREAD

**Issue by bergmark** [gf3/IRC-js#8]
Try the following sample program from the IRC-js root folder:

```
var Parser = require('./lib/parser_grammar');

var raws = [
    ':n!u@h JOIN :#chan',
    ':n`!u@h JOIN :#chan'
];

for (var i = 0; i < raws.length; i++) {
    var raw = raws[i];
    console.log(raw);
    console.log(Parser.parse(raw + "\r\n"));
}
```

The parse of the second raw fails because of the backtick (other nicks with backticks also fail)

 I tried finding the error in parser_grammar, the first raw gives the parse result seen below, indicating that the message starts of with a Person which is appropriate. The regex for nicks in a Person is /^[-[]|_\w`\\{}\^]+/, but I don't see why this wouldn't match "n`" ( note that /^[-[]|_\w`\\{}\^]+/.test("n`") => true).

Any clues why this might fail?

```
{ type: 'message'
, matchlength: 20
, offset: 0
, children: 
   [ { type: 'person'
     , matchlength: 5
     , offset: 1
     , children: [Object]
     , value: undefined
     }
   , { type: 'command'
     , matchlength: 4
     , offset: 7
     , children: []
     , value: [Object]
     }
   , { type: 'params'
     , matchlength: 7
     , offset: 11
     , children: [Object]
     , value: undefined
     }
   ]
, value: undefined
}
```

**Comment by bergmark** [comment]
Okay, i failed to give up. I found out that changing the Prefix declaration from
    Grammar.Prefix    = [":", Or(Server,Person), Space];
to
    Grammar.Prefix    = [":", Or(Person,Server), Space];
lets this raw be parsed. But I have no idea whether this will break parsing of other raws. Will write some test cases.

**Comment by bergmark** [comment]
I tried to find a way to guarantee that server names and persons were always parsed as the correct non-terminal, but since a server name may be any valid host name I'm pretty sure that this can sometimes be ambiguous.

A quick fix would be to assume that server names always contain a period ".". Is this acceptable? I'll run with it for now and attach a fix.

**Comment by bergmark** [comment]
Fix: http://github.com/Raevel/IRC-js/commit/d35d7badee4413ed814a49e2d0f1d9a4811aee89

(Run tests with `expresso -i lib`)

**Comment by gf3** [comment]
Hey Adam, I've been looking into this for a while. Unfortunately a period in the server name is not guaranteed (e.g.: localhost). I genuinely think this is a bug in Kouprey (which is no longer supported), and I'm actually in the process of switching over to inimino's [PanPG](http://github.com/azatoth/PanPG).

**Comment by bergmark** [comment]
Yeah... not a perfect solution by any means, but it'll keep my bots from crashing at least :-)

**Comment by gf3** [comment]
I'm getting close to done! I have the grammar written, and I've separated the Parser/Walker/Compiler. Should be much easier to test as well.

**Comment by bergmark** [comment]
You are awesome!

**Comment by gf3** [comment]
Fixed! Also I added some specs. c91a309b5b66883a9f8660a2736b849a77327c91
