### ISSUE TITLE
Undocumented change in raw parsing

### ISSUE THREAD

**Issue by bergmark** [gf3/IRC-js#9]
Trying out the new panpg parser now, and i noticed a difference in how it groups what it parses (in at least one case). Before when a 353 (NAMES list) was received, the message hash looked like this:

```
{ server: 'irc.server'
, command: '353'
, params: [ 'nick', '=', '#chan', ['nick', 'nick2'] ]
, raw: ':irc.server 353 nick = #chan :nick nick2'
}
```

this has now changed into:

```
{ server: 'irc.server'
, command: '353'
, params: [ 'nick = #chan', 'nick nick2' ]
, raw: ':irc.server 353 nick = #chan :nick nick2\r\n'
}
```

So the differences:
- Params seems to split into an array on : only, whereas it used to split on whitespace and group items after the : in an array.
- Raw now ends with "\r\n".

Was this intentional?
Not a huge deal for me either way, just want to know what to expect.
Also, I don't mind api changes, but if it was intentional, please try to document these changes in the commit message. Would be sweet!

In other news: Great work!

**Comment by gf3** [comment]
Hey, sorry about that. The addition of `\r\n` to `raw` is intentional, so it can be re-parsed if needed. But the params changes are a bug, good catch, for that message it should look like this: `[ 'nick', '=', '#chan', 'nick nick2' ]`.

**Comment by gf3** [comment]
Fixed in: c7f1573512032d55e0d09e8a2c1d6190795988e2

**Comment by bergmark** [comment]
Marry me

**Comment by gf3** [comment]
Hahaha
